[package]
name = "warmup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring = "0.16.20"
serde = { version = "1.0.137", features = ["derive"] }
bincode = "1.3.3"
hex = "0.4.3"
log = "0.4.17"